# Generated by Django 4.2.16 on 2025-04-10 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RQCReviewerOptingDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opting_status', models.IntegerField(choices=[(30, 'RQC_OPTING_STATUS_UNDEFINED'), (31, 'RQC_OPTING_STATUS_OPT_IN'), (32, 'RQC_OPTING_STATUS_OPT_OUT')], default=30)),
                ('opting_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RQC Opting Decision',
                'verbose_name_plural': 'RQC Opting Decisions',
            },
        ),
    ]
